language: java
jdk: oraclejdk8

dist: xenial

addons:
  firefox: "56.0"

# disable default mvn install
install: true

notifications:
  slack: qaengineering:eTRqy0JhQOUtKHNO8mKLc8NC

env:
  global:
    - CAPTURE_URL="https://capture.unity.perimeterusa.com:5000"
    - SUT_NAME="frameworkium-core"
    - SUT_VERSION=${TRAVIS_BRANCH}
    - THREAD_COUNT=2
    - SELENIUM_MAJ_VER=3.5
    - SELENIUM_VER=${SELENIUM_MAJ_VER}.3
    - SELENIUM_JAR=selenium-server-standalone-${SELENIUM_VER}.jar
    - GECKO_VER=0.19.0
    - CHROME_DRIVER_VER=2.31

# setup X to allow non-headless browsers to run
before_script:
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -q
  
  # Download geckodriver
  - wget --quiet --no-check-certificate https://github.com/mozilla/geckodriver/releases/download/v${GECKO_VER}/geckodriver-v${GECKO_VER}-linux64.tar.gz
  - tar -xzf geckodriver-v${GECKO_VER}-linux64.tar.gz --directory /tmp
  
  # Run on Firefox off the grid
  # Currently (Aug-2017) only seems to work with 1 thread on travis
  - mvn verify -B -Dthreads=1 -Dbrowser=firefox -Dwebdriver.gecko.driver=/tmp/geckodriver 2> /dev/null

  # Run on Firefox off the grid by reusing the same browser
  - mvn verify -B -Dthreads=1 -Dbrowser=firefox -DreuseBrowser=true -Dwebdriver.gecko.driver=/tmp/geckodriver 2> /dev/null

  # Download and setup Grid
  - wget --quiet --no-check-certificate https://selenium-release.storage.googleapis.com/${SELENIUM_MAJ_VER}/${SELENIUM_JAR}
  - java -Xmx128m -jar ${SELENIUM_JAR} -role hub > /dev/null 2>&1 &

  # Download and setup Marionette/geckodriver grid node
  - java -Xmx128m -Dwebdriver.gecko.driver=/tmp/geckodriver -jar ${SELENIUM_JAR} -role node -hub http://localhost:4444/grid/register -browser browserName=firefox,maxInstances=${THREAD_COUNT} -maxSession ${THREAD_COUNT} -port 5555 > /dev/null 2>&1 &

  # set up chrome
  #- ln -s /usr/bin/chromium-browser /tmp/google-chrome
  #- wget http://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VER}/chromedriver_linux64.zip --quiet
  #- unzip chromedriver_linux64.zip
  #- java -jar ${SELENIUM_JAR} -role node -hub http://localhost:4444/grid/register -browser browserName=chrome,maxInstances=${THREAD_COUNT} -port 5556 > /dev/null 2>&1 &


  # Run on Firefox on the grid via gecko
  - mvn verify -B -Dthreads=${THREAD_COUNT} -Dconfig=FirefoxGrid.yaml -DcaptureURL=${CAPTURE_URL} -DsutName="${SUT_NAME}" -DsutVersion="${SUT_VERSION}"

  # Run on chrome on the grid
  # chromium crashes and google chrome doesn't work on travis
  # - mvn verify -Dthreads=${THREAD_COUNT} -Dbrowser=chrome -DgridURL=http://localhost:4444/wd/hub -DcaptureURL=${CAPTURE_URL} -DsutName="${SUT_NAME}" -DsutVersion="${SUT_VERSION}"

  # Run and log to Jira
  - mvn verify -B -Dthreads=${THREAD_COUNT} -Dconfig=FirefoxGrid.yaml -DjiraURL="http://52.29.130.45:8080" -DjqlQuery="issueKey=TEST-1" -DresultVersion="BUILD TEST VERSION" -DzapiCycleRegex="Test Cycle" -DjiraUsername=frameworkium -DjiraPassword=frameworkium

  # Run using custom browserImpl (and subset of tests)
  - mvn verify -B -Dthreads=${THREAD_COUNT} -DcustomBrowserImpl=CustomFirefoxImpl -Dwebdriver.gecko.driver=/tmp/geckodriver -Dit.test=DocumentationTest 2> /dev/null

  # Run on sauce
  # - mvn verify -Dsauce=true -Dplatform=ios -Dbrowser=safari -DplatformVersion=8.0 -Ddevice=iPad -DcaptureURL=${CAPTURE_URL} -DsutName="${SUT_NAME}" -DsutVersion="${SUT_VERSION}"

  # generate allure report
  - mvn site -B -q
